### PR TITLE
Chef 16 Fixes

### PR DESCRIPTION
**Pull request by zimmerry**

### CODE REVIEW

**Comment by zimmerry** [comment]
[Chef 16: yum-qemu-ev](https://trello.com/c/FNgDLmAO/1984-chef-16-yum-qemu-ev)

**Review by ramereth — APPROVED** [review]
Please do a patch bump

**Comment by zimmerry** [comment]
!bump patch *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.5.1.  Have a nice day!

**Pull request merged**
